language: python

python: "3.7"

os: linux

before_install:
#  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml
#  - mv customize_sample.yaml customize.yaml
#  - "sudo mkdir -p /ssl/ && sudo touch /ssl/fullchain.pem"
#  - "sudo mkdir -p /ssl/ && sudo touch /ssl/privkey.pem"
#  - "sudo mkdir -p /config/tmp"
  - sudo apt-get install -y libudev-dev
  - pip install getmac==0.8.1
#dependencies
  - git clone https://github.com/jomwells/ambilights.git
  - cd ambilights/
  - mv custom_components/ ..
  - cd ..
  - git clone https://github.com/custom-components/breaking_changes.git
  - mv breaking_changes/custom_components/breaking_changes/ ./custom_components/
  - git clone https://github.com/pilotak/homeassistant-attributes.git
  - mv homeassistant-attributes/custom_components/attributes/ ./custom_components/
  - git clone https://github.com/Danielhiversen/home_assistant_tractive.git
  - mv home_assistant_tractive/custom_components/tractive/ ./custom_components/
  - git clone https://github.com/custom-components/sensor.unifigateway.git
  - mv sensor.unifigateway/custom_components/unifigateway/ ./custom_components/
  - git clone https://github.com/nstrelow/ha_philips_android_tv.git
  - mv ha_philips_android_tv/custom_components/philips_android_tv/ ./custom_components/
  - git clone https://github.com/mercs600/ha-adb_service.git
  - mv ha-adb_service/custom_components/adb_service/ ./custom_components/
  - git clone https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net.git
  - mv Home-Assistant-custom-components-Burze.dzis.net/custom_components/burze_dzis_net/ ./custom_components/
  - git clone https://github.com/mrk-its/homeassistant-blitzortung.git
  - mv homeassistant-blitzortung/custom_components/blitzortung/ ./custom_components/
  - git clone https://github.com/StyraHem/ShellyForHASS.git
  - mv ShellyForHASS/custom_components/shelly/ ./custom_components/
  - git clone https://github.com/bieniu/ha-airly.git
  - mv ha-airly/custom_components/airly/ ./custom_components/
  - git clone https://github.com/benct/lovelace-battery-entity-row
  - mv lovelace-battery-entity-row/ ./custom_components/ 
  - git clone https://github.com/benct/lovelace-xiaomi-vacuum-card
  - mv lovelace-xiaomi-vacuum-card/ ./custom_components/
  - git clone https://github.com/Limych/ha-average
  - mv ha-average/custom_components/average/ ./custom_components/
  - git clone https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
  - mv Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/custom_components/xiaomi_cloud_map_extractor/ ./custom_components/



install:
  - pip3 install homeassistant


script:
  - hass --version
  - "hass -c . --script check_config --info all"
#  - "hass -c . --script check_config --info all | tee check.output"
#  - '! less check.output | grep -q "Failed config"'
