
homeassistant:
  name: Centrum dowodzenia
  latitude: !secret lat
  longitude: !secret long
  elevation: 431
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  packages: !include_dir_named packages

#breaking_changes:

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmo_url
  vscode:
    title: VSCode
    url: !secret vscode_url
    icon: mdi:bug

frontend:
  themes: !include_dir_merge_named themes

system_health:

config:

mobile_app:

http:

updater:
  include_used_components: true

conversation:

map:

sun:

cloud:

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 32
  include:
    entity_globs:
        - sensor.*energy*
        - sensor.netatmo_*
        - weather.*
        - person.*
        - sensor.speedtest*
    domains:
        - switch
        - light
#      - media_player
        - climate
        - sensor
  exclude:
    entity_globs:
      - sensor.unifi*

      - sensor.wled*
      - sensor.*wifi_signal_strength
      - sensor.*_signal_strength
      - sensor.*signal
      - sensor.*bssid

    domains:
      - camera
      - group
      - automation
      - binary_sensor
      - input_text
      - input_number
      #- sensor
      #- switch
    entities:
      - sensor.date
      - sensor.hacs
      - sensor.last_alexa
      - sensor.last_boot
      - sensor.last_tag_description
      - sun.sun
   
logger:
  default: info

discovery:
#  enable:
#    - homekit

python_script:



  tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
input_text: !include input_text.yaml
rest_command: !include rest_command.yaml
