sensor:
  - platform: qnap
    host: !secret qnap_ip
    username: !secret qnap_l
    password: !secret qnap_p
    monitored_conditions:
      - status
      - cpu_usage
      - cpu_temp
      - system_temp
      - memory_percent_used
      - memory_free
      - network_tx
      - volume_percentage_used
      - drive_temp
      - drive_smart_status