#####
# New HA version noficitaion - WORK IN PROGRESS
# https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/system/homeassistant_version.yaml
#
# &
#
# https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/automations/system/home_assistant_update_notifiication.yaml
#####

#id: c57b0367-ca6f-4e7b-8e18-307c4b44cf8b
- alias: Home Assistant Update Notification

  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.latest_version

  condition:
    - condition: template
      value_template: >
        {{
        states("sensor.latest_version") != states("sensor.current_version")
        and states("sensor.latest_version") != "unknown"
        and states("sensor.latest_version") != states("input_text.version_latest_notified")
        }}

  action:
# Set input text to latest HA value
  - service: input_text.set_value
    data:
      entity_id: input_text.version_latest_notified
      value: '{{ states("sensor.latest_version") }}'

  - service: persistent_notification.create
    data:
      title: Update Home Assistant
      message: >
        There is an update to Home Assistant Supervised
          * {{ states("sensor.current_version") }} -> {{ states("sensor.latest_version") }}
          Triggering Travis build...
      notification_id: update_ha

# First we need to open issue 2 that tracks updates
  - service: rest_command.github_issue_state
    data:
      status: "open"
      issue_number: 2

# Then we post new status to issue 2
  - service: rest_command.github_issue_comment
    data:
      message: 'Upgrade Home Assistant from {{ states("sensor.current_version") }} to {{ states("sensor.latest_version") }} \n Release notes available via {{ state_attr("binary_sensor.updater","release_notes") }}. \n \n This comment was generated by Jarvis.","labels":["task: upgrade","task: maintenance"]} '
      issue_number: 2
  - service: rest_command.travis_build

# wait for travis build to start then update notification
  - wait_template: "{{ is_state('sensor.sineczek_homeassistant_state', 'started') }}"

  - service: persistent_notification.create
    data:
      title: Update Home Assistant
      message: >
        There is an update to Home Assistant Supervised
          * {{ states("sensor.current_version") }} -> {{ states("sensor.latest_version") }}
          Travis Build has started
      notification_id: update_ha

# wait for build to complete and update notification with status
  - wait_template: "{{ not is_state('sensor.sineczek_homeassistant_state', 'created') and not is_state('sensor.sineczek_homeassistant_state', 'started') }}"

  - service: persistent_notification.create
    data:
      title: Update Home Assistant
      message: >
        There is an update to Home Assistant Supervised
          * {{ states("sensor.current_version") }} -> {{ states("sensor.latest_version") }}
          Travis Build has {{states('sensor.sineczek_homeassistant_state')}}
      notification_id: update_ha

# post issue comment on Travis status
  - service: rest_command.github_issue_comment
    data:
      message: "Travis build has {{ states('sensor.sineczek_homeassistant_state') }}"
      issue_number: 2